use_frameworks!

target 'NSArray-Extension_Example' do
  pod 'NSArray-Extension',:git=>'git@github.com:bloack/NSArray-Extension.git'

  target 'NSArray-Extension_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
